export const categories = [
    { id: "all", label: "All" },
    { id: "milk-made", label: "Milk Made" },
    { id: "dry-fruits", label: "Dry Fruits" },
    { id: "special", label: "Special" },
    { id: "besan", label: "Besan" },
    { id: "namkeen", label: "Namkeen" },
    { id: "winter-special", label: "Winter Special" },
    { id: "gift-combos", label: "Gift Combos" },
];

export const products = [
    {
        name: "Kesar Peda",
        desc: "Rich, saffron-infused milk sweet with a soft, melt-in-the-mouth texture.",
        category: 'milk-made',
        image: "/image/kesar-peda.jpeg",
        highlight: "Rich kesar flavor, no essence",
        tags: ["Kesar", "Peda", "Ghee", "Saffron", "Milk"],
        badge: true,
    },
    {
        name: "White Peda",
        desc: "Traditional milk peda made from slow-cooked khoya, with a soft texture and delicately sweet, rich flavor.",
        category: 'milk-made',
        image: "/image/white-peda.jpeg",
        highlight: "Pure milk, no additives",
        tags: ["Peda", "Ghee", "Milk"],
        badge: false,
    },
    {
        name: "Kalakand",
        desc: "Soft, grainy milk sweet made from fresh chhena and khoya, with a rich, lightly caramelized flavor.",
        category: 'milk-made',
        image: "/image/kalakand.jpeg",
        highlight: "Fresh milk, soft & grainy texture",
        tags: ["Ghee", "Milk"],
        badge: true,
    },
    {
        name: "Kaju Katli",
        desc: "Smooth, melt-in-the-mouth cashew sweet made from finely ground premium kaju.",
        category: 'dry-fruits',
        image: "/image/kaju-katli.jpeg",
        highlight: "100% pure kaju, no starch",
        tags: ["Burfi", "Kaju"],
        badge: false,
    },
    {
        name: "Kesar Pista Katli",
        desc: "Delicate blend of cashew, pista, and saffron with a smooth, melt-in-the-mouth texture.",
        category: 'dry-fruits',
        image: "/image/kesar-pista-katli.jpeg",
        highlight: "Real kesar & pista, no essence",
        tags: ["Burfi", "Kesar", "pista"],
        badge: true,
    },
    {
        name: "Motipak",
        desc: "Soft, rich milk sweet with a slightly grainy texture and a delicate, melt-in-the-mouth finish.",
        category: 'special',
        image: "/image/motipak.jpeg",
        highlight: "Rich milk base, soft & grainy texture",
        tags: ["Burfi", "pak",],
        badge: true,
    },
    {
        name: "Gulab Jamun",
        desc: "Soft, deep-fried milk dumplings soaked in fragrant sugar syrup, rich and juicy.",
        category: 'special',
        image: "/image/gulab-jamun.jpeg",
        highlight: "Soft & juicy, soaked in syrup",
        tags: ["Soft", "Mithai",],
        badge: true,
    },
    {
        name: "Bundi Laddoo",
        desc: "Roasted gram flour laddoos with a rich, nutty aroma and melt-in-the-mouth texture.",
        category: 'besan',
        image: "/image/bundi-laddoo.jpeg",
        highlight: "Pure besan, rich ghee flavor",
        tags: ["besan", "laddoo", "laddu"],
        badge: false,
    },
    {
        name: "Besan ki Barfi (Dilkushal)",
        desc: "Rich besan barfi slow-cooked in ghee, with a soft, slightly crumbly texture and deep roasted flavor.",
        category: 'besan',
        image: "/image/besan-barfi.jpeg",
        highlight: "Slow-roasted besan, rich ghee taste",
        tags: ["besan", "barfi"],
        badge: true,
    },
    {
        name: "Bhujiya",
        desc: "Crispy, spiced gram flour snack with a light texture and savory kick.",
        category: 'namkeen',
        image: "/image/sev.jpeg",
        highlight: "Crunchy sev, classic masala taste",
        tags: ["bujiya", "namkeen"],
        badge: false,
    },
    {
        name: "Chana Dal",
        desc: "Crispy roasted chana dal seasoned with light spices for a savory, crunchy bite.",
        category: 'namkeen',
        image: "/image/chana-dal.jpg",
        highlight: "Crunchy dal, lightly spiced",
        tags: ["dal", "namkeen"],
        badge: false,
    },
    {
        name: "Shahi Mixture",
        desc: "Royal mix of crunchy sev, nuts, and spices with a rich, balanced flavor.",
        category: 'namkeen',
        image: "/image/mixture.jpeg",
        highlight: "Premium mix, rich & crunchy",
        tags: ["mixture", "namkeen"],
        badge: true,
    },
    {
        name: "Mathri",
        desc: "Crispy, flaky crackers made with mild spices, offering a rich, savory flavor and satisfying crunch.",
        category: 'namkeen',
        image: "/image/mathri.jpeg",
        highlight: "Flaky crunch, classic taste",
        tags: ["mathri", "namkeen"],
        badge: false,
    },
    {
        name: "Gudpak",
        desc: "Nutritious sweet made with edible gum, ghee, and dry fruits, offering a rich, dense texture and warming taste.",
        category: 'winter-special',
        image: "/image/gudpak.jpeg",
        highlight: "Energy-rich, loaded with penuts",
        tags: ["gud", "winter"],
        badge: true,
    },
    {
        name: "Anarkali (Gud ki Sall)",
        desc: "Traditional jaggery-based sweet with a crisp bite and deep, earthy sweetness.",
        category: 'winter-special',
        image: "/image/anarkali.jpeg",
        highlight: "Pure gud, rich desi taste",
        tags: ["gud", "winter"],
        badge: false,
    },
    {
        name: " Gajak",
        desc: "Traditional sesame and jaggery sweet with a crisp texture and rich, nutty flavor.",
        category: 'winter-special',
        image: "/image/gajak.jpg",
        highlight: "Til & gud, crisp layers",
        tags: ["gajak", "winter"],
        badge: false,
    },
    {
        name: "Wedding Gift Box",
        desc: "An heirloom assortment for the most cherished celebrations — kaju katli, motichoor, ghewar, and silver-leaf burfis.",
        category: 'gift-combos',
        image: "/image/hamper-wedding.jpg",
        highlight: "Premium wedding gift box",
        tags: ["hamper", "wedding"],
        badge: false,
    },
    {
        name: "Festive Combo",
        desc: "Diwali, Holi, Rakhi — a curated mix of seasonal favourites.",
        category: 'gift-combos',
        image: "/image/hamper-festive.jpg",
        highlight: "Perfect celebration pack",
        tags: ["hamper", "festive"],
        badge: false,
    },
    {
        name: "Corporate Hampers",
        desc: "Elegant, brand-friendly hampers for clients and teams.",
        category: 'gift-combos',
        image: "/image/hamper-corporate.jpg",
        highlight: "Professional & festive gifting",
        tags: ["hamper", "festive"],
        badge: false,
    },
    {
        name: "Kesar Ghevar",
        desc: "A traditional Rajasthani sweet with a delicate honeycomb texture, infused with rich saffron and topped with nuts.",
        category: 'special',
        image: "/image/ghevar.jpeg",
        highlight: "Pure desi ghee & Premium saffron infusion",
        tags: ["Soft", "Mithai",],
        badge: true,
        outOfStock: true,
    },

];